# Generated by Django 5.0 on 2026-05-01 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CTraderCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('_client_secret', models.TextField(db_column='client_secret')),
                ('_access_token', models.TextField(db_column='access_token')),
                ('account_id', models.BigIntegerField()),
                ('is_live', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ctrader_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_id', models.BigIntegerField()),
                ('position_id', models.BigIntegerField()),
                ('direction', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fill_price', models.DecimalField(decimal_places=5, max_digits=18)),
                ('close_price', models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True)),
                ('pnl', models.DecimalField(decimal_places=2, max_digits=18)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_closing', models.BooleanField(default=True)),
                ('executed_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trading.symbol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['user', '-executed_at'], name='trading_tra_user_id_7b62ae_idx'), models.Index(fields=['user', 'symbol'], name='trading_tra_user_id_68f61e_idx')],
                'unique_together': {('user', 'deal_id')},
            },
        ),
    ]
